# Generated by Django 3.2.6 on 2021-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('Cpassword', models.CharField(max_length=70)),
                ('dob', models.DateField(max_length=70)),
                ('gender', models.CharField(max_length=70)),
                ('hobbies', models.CharField(max_length=150)),
            ],
        ),
    ]
