# Generated by Django 3.2.6 on 2021-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='Cpassword',
        ),
    ]
