# Generated by Django 3.2.6 on 2021-09-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
